config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
end


# A user can see all the lists
# GET "lists"
# A user can see the details of a given list and its name
# GET "lists/42"
# A user can create a new list
# GET "lists/new"
# POST "lists"

# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"
# DELETE "bookmarks/25"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates :movie_id, :list_id, :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'bookmarks/new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'lists/new', status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon-black fixed-top">
  <div class="container">
    <span class="logo"><%= link_to "CINEFLIX", lists_path %></span>
    <button class="btn-cineflix"><%= link_to "Create List", new_list_path(@list) %></button>
  </div>
</nav>

<div class="container my-5 w-50">
  <h1 class="border-bottom border-dark mb-5 pb-2 pt-5"><%= @list.name %>: Add a Movie</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment, label: 'Comment' %>
    <%= f.submit "Add" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cineflix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= yield %>
    <footer class="footer">
      <div class="container">
        <div class="social-icons-wrapper">
          <a href="#"><i class="fa-brands fa-instagram"></i></a>
          <a href="#"><i class="fa-brands fa-twitter"></i></a>
          <a href="#"><i class="fa-brands fa-youtube"></i></a>
          <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
          <a href="#"><i class="fa-brands fa-spotify"></i></a>
        </div>
        <p>©2023 Cineflix Ltd.</p>
      </div>
    </footer>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container">
    <span class="logo"><%= link_to "CINEFLIX", lists_path %></span>
    <button class="btn-cineflix"><%= link_to "Create List", new_list_path(@list) %></button>
  </div>
</nav>

<div class="banner" style="background-image: linear-gradient(rgba(255,250,249,0.2),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1462715412043-8d09205be605?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1>Explore & Discover Your Favourite Movies</h1>
  </div>
</div>

<div class="container my-5">
  <div class="row gx-3 card-row">
    <% @lists.each do |list| %>
      <div class="col-lg-4" style="padding: 0.5rem;">
        <div class="card-list" style="background-image: linear-gradient(rgba(255,250,249,0.1),rgba(0,0,0,0.6)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>); background-size: cover;">
          <h1><%= link_to list.name, list_path(list) %></h1>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon-black fixed-top">
  <div class="container">
    <span class="logo"><%= link_to "CINEFLIX", lists_path %></span>
    <button class="btn-cineflix"><%= link_to "Create List", new_list_path(@list) %></button>
  </div>
</nav>

<div class="container my-5 w-50">
  <h1 class="border-bottom border-dark mb-5 pb-2 pt-5">Create a New List</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container">
    <span class="logo"><%= link_to "CINEFLIX", lists_path %></span>
    <button class="btn-cineflix"><%= link_to "Create List", new_list_path(@list) %></button>
  </div>
</nav>

<div class="banner" style="height: 20vh; background-image: linear-gradient(rgba(255,250,249,0.2),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, width: 1200, crop: :fill %>);">
</div>

<div class="container my-5">
  <h1 class="border-bottom border-dark mb-3"><%= @list.name %> Movies</h1>
  <button class="btn-cineflix"><%= link_to "Add a Movie", new_list_bookmark_path(@list) %></button>

  <div class="row">
    <% @bookmarks.each do |bookmark| %>
      <div class="col-lg-4" style="padding: 1rem;">
        <div class="py-4 border-bottom border-dark">
          <img src="<%= bookmark.movie.poster_url %>" alt="" style="width: 100%;">
          <h2 class="mt-4"><%= bookmark.movie.title %></h2>
          <span class="movie-rating">Rating: <%= bookmark.movie.rating %></span>
          <p><%= bookmark.movie.overview %></p>
          <button class="btn-cineflix mb-2"><%= link_to bookmark, data: {turbo_method: :delete, turbo_confirm: "Delete #{bookmark.movie.title}?"} do %>
            Delete
          <% end %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>